runtime: python27
api_version: 1
threadsafe: true

handlers: #Need to know where to go in the first place

- url: .* #if you go here, we run this script
  script: TotalProject.application

libraries: #We need this stuff to run this code
- name: webapp2
  version: latest
- name: jinja2
  version: latest
